# Generated by Django 5.0.6 on 2024-07-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_rename_contact_ticket_reporter_organization_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
