# Generated by Django 5.0.6 on 2024-07-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_orgticketcounter_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
